### ISSUE TITLE
useSubstrate roadmap

### ISSUE THREAD

**Issue by krzysztof-jelski** [EthWorks/statemine-asset-creator#102]
## First release
- [ ] Separate repository + publish on NPM
- [ ] Handle other transaction statuses [ready -> in block -> finalized]
- [ ] Support events/callbacks for transaction status changes
- [ ] `useAssetBalance` hook for Statemin* assets
- [ ] Query info about decimals, unit of a specific chain (`useChainSpec`)
- [ ] Short research of similar libraries
- [ ] Docs/release announcement

## Second release
- [ ] Support Polkadot/Statemint as pre-configured chains

## Future ideas:

- [ ] Hook for NFTs (`uniques` pallete)
